name: Python Application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python App Docker Test
        id: python-app
        uses: ./.github/actions/docker-python-action
        with:
          version: v2.0.0
      - name: Get Docker results
        run: echo "${{ steps.python-app.outputs.result }}"
      - name: Set variables for coverage badge
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          echo $REPO_NAME
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

          REF=${{ github.ref }}
          echo "github.ref: $REF"
          IFS='/' read -ra PATHS <<< "$REF"

          BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
          echo $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

          FILENAME="${REPO_NAME}__${BRANCH_NAME}.json"
          echo $FILENAME
          echo "FILENAME=${FILENAME}" >> $GITHUB_ENV
